name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare repository
        uses: iktnb/github-utils/.github/actions/prepare-repo@v1
        with:
          node-version: "20"

      - name: Configure Git for push
        uses: iktnb/github-utils/.github/actions/configure-git-push@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Storybook
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
        run: npm run build-storybook

      - name: Ensure CNAME file
        uses: iktnb/github-utils/.github/actions/ensure-cname@v1
        with:
          site_url: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          output_path: storybook-static

      - name: Deploy
        run: npm --ignore-scripts run deploy
